#!/bin/zsh
# milomouse <vincent[at]fea.st>
# NOTE: Remembers songs and plays them back later, also show songs in list.
#       Idea from "GoodSong"; although I didn't adopt ideas I didn't want.

# file location for remembered song list:
list="/home/yamifrankc/scripts/.songrem"
[ -f $list ] || touch $list

# check if song exists in $list:
song="$(mpc --format "%artist% - \"%title%\" (%album%)"|sed '2,$d')"
check=$(grep "$song" "$list")

# usage display:
help_message() {
<< EOF
usage: songrem [OPTION]

    -p | --play   Plays a random song from existing
                  list by matching it against the
                  current running playlist.

    -a | --add    Adds current song to your list.

    -r | --remove Remove current song from list if
                  found, otherwise do nothing.

    -e | --edit   Edit list manually from terminal.

    -s | --show   Display all songs in your list,
                  or search by pattern, like:
                  songrem -s "animal collective"

    -h | --help   Display this message and exit.
EOF
}

# parse the options:
case $1 in
  -s|--show)
  if [ -z "$2" ]; then
    <$list
  else
    <$list|grep -i "$@"
  fi
  ;;
  -e|--edit)
    ${EDITOR:-vim} $list
  ;;
  -r|--remove)
  if [[ $(mpc|head -1|wc -c) -gt 36 ]]; then
    nmbr=$(echo $(mpc|head -1|cut -c1-36) "..")
  else
    nmbr=$(echo $(mpc|head -1|cut -c1-36))
  fi
  if [ -n "$check" ]; then
    for pos in $(<$list|grep -B 99999 $check|wc -l); do
      temp=$(mktemp)
      cp $list $temp
      <$temp|sed ''"$pos"'d' >! $list
      rm -f $temp >&/dev/null
    done
    if [[ -n $(pgrep xmonad) || -n $(pgrep musca) ]]; then
      echo "\"$nmbr\" ^fg(#007b8c)removed from list" | dzen2 -p 4 -ta 'r' -h '13' -w '354' -x '635' -y '0' -bg '#161616' -fg '#a9a6af' -fn '-*-fixed-medium-r-normal-*-10-*-*-*-*-*-*-*'
    else
      echo "\"$nmbr\" removed from list"
    fi
  else
    :
  fi
  ;;
  -p|--play)
    mpc play $(mpc playlist --format "%artist% - \"%title%\" (%album%)"|\
    grep "$(<$list|sort -R|sed '2,$d')"|awk '{print $1}'|tr -cd '[0-9]') >&/dev/null

    _one=$(print -n "$(mpc|sed '2,$d')")
    _two=$(print -n ">>> $(mpc|sed '3,$d;2,$!d'|awk '{print $3" "$2}')")
    _info=$(print -n $_one $_two)
#    if [[ -n $(pgrep xmonad) || -n $(pgrep musca) ]]; then
#      echo "$_info"
#    else
      print "$_info"
#    fi
  ;;
  -a|--add)
  if [[ -n $(mpc|sed '2,$d'|grep "volume:") ]]; then
    exit 0
  elif [ -z "$check" ]; then
  if [[ $(mpc|head -1|wc -c) -gt 40 ]]; then
    nmbr=$(echo $(mpc|head -1|cut -c1-40) "..")
  else
    nmbr=$(echo $(mpc|head -1|cut -c1-40))
  fi
    print "$song" >> "$list"
    _info=$(print \"$nmbr\")
    if [[ -n $(pgrep xmonad) || -n $(pgrep musca) ]]; then
      echo "$_info ^fg(#007b8c)added to list" | dzen2 -p 4 -ta 'r' -h '13' -w '354' -x '635' -y '0' -bg '#161616' -fg '#a9a6af' -fn '-*-fixed-medium-r-normal-*-10-*-*-*-*-*-*-*'
    else
      print "$_info added to list"
    fi
  else
  if [[ $(mpc|head -1|wc -c) -gt 38 ]]; then
    nmbr=$(echo $(mpc|head -1|cut -c1-38) "..")
  else
    nmbr=$(echo $(mpc|head -1|cut -c1-38))
  fi
    _info=$(print "\"$nmbr"\")
    if [[ -n $(pgrep xmonad) || -n $(pgrep musca) ]]; then
      echo "$_info ^fg(#007b8c)already in list" | dzen2 -p 4 -ta 'r' -h '13' -w '354' -x '635' -y '0' -bg '#161616' -fg '#a9a6af' -fn '-*-fixed-medium-r-normal-*-10-*-*-*-*-*-*-*'
    else
      print "$_info already in list"
    fi
  fi
  ;;
  -h|--help|*)
    help_message
  ;;
esac

exit 0
