#!/bin/zsh

if [ -x /usr/bin/display ]; then
   dir=$HOME/wallpapers
   get=$(find $dir/*|grep -ie '.png\|.jpg\|.jpeg\|.gif' | sort -R | tail -1)
   display -window root -resize $(xdpyinfo|grep dimensions|awk '{print $2}')! $get
fi
